# Generated by Django 5.0.2 on 2024-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doctor_organisation_alter_organisation_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
