# Generated by Django 5.0.2 on 2024-03-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hospital_remove_doctor_organisation_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='any_report',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='previously_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_for',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
